### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 4096 and 1024. Shapes are [4096,2048] and [1024,2048].

### ISSUE THREAD

**Issue by arturpol94** [kentsommer/tensorflow-posenet#10]
Hey,

I was trying to train PoseNet on the 'KingsCollege' dataset but I am struggling with the following error. 
Haven't changed anything in the code yet.
Could you help me with that?

Cheers

Artur

ERROR LOG:
100%|██████████| 1220/1220 [00:38<00:00, 31.66it/s]
100%|██████████| 1220/1220 [00:00<00:00, 2945.12it/s]
100%|██████████| 1220/1220 [00:01<00:00, 1201.31it/s]
2018-12-04 18:04:12.270916: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/n10294651/Desktop/PhD_QUT/PROJECTS/POSENET_11_2018/tensorflow-posenet-master/train.py", line 170, in <module>
    main()
  File "/home/n10294651/Desktop/PhD_QUT/PROJECTS/POSENET_11_2018/tensorflow-posenet-master/train.py", line 151, in main
    net.load('/home/n10294651/Desktop/PhD_QUT/PROJECTS/POSENET_11_2018/tensorflow-posenet-master/weights/posenet.npy', sess)
  File "network.py", line 65, in load
    session.run(var.assign(data))
  File "/home/n10294651/venv_python2.7/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 1718, in assign
    name=name)
  File "/home/n10294651/venv_python2.7/local/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "/home/n10294651/venv_python2.7/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "/home/n10294651/venv_python2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/n10294651/venv_python2.7/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/n10294651/venv_python2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/n10294651/venv_python2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/home/n10294651/venv_python2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 4096 and 1024. Shapes are [4096,2048] and [1024,2048]. for 'cls3_fc1_pose_1/Assign' (op: 'Assign') with input shapes: [4096,2048], [1024,2048].

**Comment by kentsommer** [comment]
Closing this out after a long hiatus from Github. There have been a lot of updates across many of the utilized frameworks since this was published. Unfortunately I do not have the time to update it which is most likely why these issues are cropping up.

I will happily merge in any pull requests if folks have a desire to keep this working.
